# Generated by Django 3.2.8 on 2023-11-03 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='pics')),
                ('phone', models.BigIntegerField(default=None, null=True)),
                ('profession', models.CharField(default=None, max_length=50, null=True)),
                ('experience', models.CharField(default=None, max_length=50, null=True)),
                ('rate', models.IntegerField(default=None, null=True)),
                ('eng_level', models.CharField(default=None, max_length=10, null=True)),
                ('completedProjectNo', models.IntegerField(default=None, null=True)),
                ('availability', models.IntegerField(default=None, null=True)),
                ('bio', models.TextField(default=None, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='account.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
