# Generated by Django 3.2.8 on 2023-11-03 23:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images')),
                ('sampleLink', models.URLField(blank=True, null=True)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
                ('slug', models.SlugField(blank=True, default='tutorial', null=True)),
                ('subject', models.ManyToManyField(blank=True, to='account.Skill')),
            ],
        ),
    ]
