# Generated by Django 3.2.8 on 2023-11-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(default='python', max_length=200),
            preserve_default=False,
        ),
    ]
