# Generated by Django 3.2.8 on 2021-10-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_alter_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
