# Generated by Django 3.2.8 on 2021-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0003_alter_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='www', null=True),
        ),
    ]
