# Generated by Django 3.2.8 on 2021-10-14 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0004_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
