# Generated by Django 3.2.8 on 2021-11-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0006_alter_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deploylink',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='githublink',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
