# Generated by Django 3.2.8 on 2021-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, upload_to='pics')),
                ('img2', models.CharField(default='sunset,girl', max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
