# Generated by Django 3.2.8 on 2021-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(default='', max_length=122)),
                ('email', models.EmailField(max_length=122, primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Crausal',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.CharField(default='mountain', max_length=50)),
                ('ctext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('title', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
                ('desc', models.CharField(default='', max_length=150)),
                ('img', models.CharField(default='', max_length=30)),
                ('minRead', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('subject', models.CharField(default='xyz', max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
            ],
        ),
    ]
