# Generated by Django 3.2.8 on 2021-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crausal',
            name='img1',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='img',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
