# Generated by Django 3.2.8 on 2021-10-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211012_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crausal',
            name='img1',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
