# Generated by Django 3.2.8 on 2021-11-03 22:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211012_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(blank=True, default='tutorial', null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
