# Generated by Django 3.2.8 on 2023-11-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211103_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='sampleLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
