# Generated by Django 3.2.8 on 2021-11-02 19:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('quesno', models.BigIntegerField(default='00', primary_key=True, serialize=False)),
                ('ques', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=10)),
                ('exp', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectiveQues.ques')),
            ],
        ),
    ]
