# Generated by Django 3.2.8 on 2021-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='pics')),
                ('mfgDate', models.DateField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
            ],
        ),
    ]
