# Generated by Django 3.2.8 on 2021-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turistingo',
            fields=[
                ('city', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField(default=10000)),
                ('dis', models.IntegerField(default=0)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
